FROM tomcat:9.0.1-alpine

COPY dockerfiles/tomcat-users.xml /usr/local/tomcat/conf/
COPY dockerfiles/context.xml /usr/local/tomcat/webapps/manager/META-INF/context.xml

#RUN rm -rf /usr/local/tomcat/webapps/ROOT

CMD ["catalina.sh", "run"]
