insert into varchar_test(id, varchar_col) values(1, '1234567890');
insert into varchar_test(id, varchar_col) values(2, '一二三');
insert into varchar_test(id, varchar_col) values(3, '一𪘂𪗱');
insert into varchar_test(id, varchar_col) values(4, '一二三四');
insert into varchar_test(id, varchar_col) values(5, '一二三四五六七八九十');
insert into varchar_test(id, varchar_col) values(6, '𠀋𡈽𡌛𡑮𡢽𠮟𡚴𡸴𣇄𣗄');
insert into varchar_test(id, varchar_col) values(7, '12345678901');
insert into varchar_test(id, varchar_col) values(8, '一二三四五六七八九十一');
insert into varchar_test(id, varchar_col) values(9, '𠀋𡈽𡌛𡑮𡢽𠮟𡚴𡸴𣇄𣗄𣜿');
