version: '3'

services:
    workspace:
        build:
            context: ..
            dockerfile: .devcontainer/Dockerfile
        environment:
            PYTHONPATH: /workspace
        volumes:
            - ../src:/workspace
            - ../.git:/workspace/.git # .gitディレクトリを共有
        command: sleep infinity