version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    restart: always
    environment:
      - KB_ID=${KB_ID}
    volumes:
      - "~/.aws:/root/.aws"